### ISSUE TITLE
Local 'db' has already been initialized.

### ISSUE THREAD

**Issue by keithmarsh** [joaquimguimaraes/farmr#198]
1.8.1.5 installed with .deb
remove ~/.farmr
chia now at 1.4.0
starting farmr gives

```
Starting farmr for chia in Farmer mode...
Unhandled exception:
LateInitializationError: Local 'db' has already been initialized.
#0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:204)
#1      openSQLiteDB (package:farmr_client/utils/sqlite.dart:16)
#2      Cache._createTables (package:farmr_client/cache/cacheIO.dart:40)
#3      new Cache (package:farmr_client/cache/cacheIO.dart:34)
#4      Blockchain.init (package:farmr_client/blockchain.dart:237)
#5      main (file:///home/runner/work/farmr/farmr/farmr.dart:180)
<asynchronous suspension>
```

**Comment by Melbar666** [comment]
getting the same error since chia update to 1.4.0

**Comment by cdgraff** [comment]
+1 same here

**Comment by ZwaZo22** [comment]
+1 here as well (chia 1.4 on ubuntu)

**Comment by kvizena** [comment]
Same issue with Chia 1.5.0 running v1.8.1.5.

**Comment by kvizena** [comment]
The sqllite changes in v1.8.1.4 seem to be the problem. 

Run v1.8.1.3 and it works in Debian on my NAS, as well as a couple of my Fedora machines as well.

**Comment by ZwaZo22** [comment]
> The sqllite changes in v1.8.1.4 seem to be the problem.
> 
> Run v1.8.1.3 and it works in Debian on my NAS, as well as a couple of my Fedora machines as well.

Thanks @kvizena ! I confirm that It's working by downgrading to the v.1.8.1.3 on Ubuntu / Chia v.1.4.

**Comment by OutsmartinTech** [comment]
Same problem as others, can also confirm that downgrading to v1.8.1.3 worked for me as well.

**Comment by JaroslavHorky** [comment]
Hello, Can someone tell me how to install it?

I install it like this:

```
curl -0 https://guthub.com/gilnobrega/farmr/releases/download/v1.8.1.3/farmr-ubuntu-x86_64.deb
sudo apt install farmr-ubuntu-x86_64.deb
```

and I get this message :-(

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package farmr-ubuntu-x86_64.deb
```

Thanks for help

**Comment by cdgraff** [comment]
@JaroslavHorky you need install with dpkg

`sudo dpkg -i farmr-ubuntu-x86_64.deb`

**Comment by JaroslavHorky** [comment]
> @JaroslavHorky you need install with dpkg
> 
> `sudo dpkg -i farmr-ubuntu-x86_64.deb`

Great @cdgraff . Thank you.

it works now. 
I can only see half of my farm on farmr.net. I have two servers=two harvesters connected to each other. So do I have to install the same thing on the second linux server as well? Then I will see two farmers separately? Can it be connected somehow?

Thank you
