### ISSUE TITLE
Unhandled exception:

### ISSUE THREAD

**Issue by JaroslavHorky** [joaquimguimaraes/farmr#202]
Hello, I'm trying to run farmr. I have the installation on an Ubuntu server. After running I get this error. I have no idea what to do next.

`Unhandled exception:
LateInitializationError: Local 'db' has already been initialized.
#0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:204)
#1      openSQLiteDB (package:farmr_client/utils/sqlite.dart:16)
#2      Cache._createTables (package:farmr_client/cache/cacheIO.dart:40)
#3      new Cache (package:farmr_client/cache/cacheIO.dart:34)
#4      Blockchain.init (package:farmr_client/blockchain.dart:237)
#5      main (file:///home/runner/work/farmr/farmr/farmr.dart:180)
<asynchronous suspension>`

Thanks for help

**Comment by OutsmartinTech** [comment]
I'm getting the exact same error. I upgraded from v1.7 and got this error. I then tried uninstalling v1.8, removing the .farmr folder and then reinstalling v1.8. I still get the error. I'm using Ubuntu server as well (v20.04.4 LTS).

```
Starting farmr for chia in Farmer mode...
Unhandled exception:
LateInitializationError: Local 'db' has already been initialized.
#0      LateError._throwLocalAlreadyInitialized (dart:_internal-patch/internal_patch.dart:204)
#1      openSQLiteDB (package:farmr_client/utils/sqlite.dart:16)
#2      Cache._createTables (package:farmr_client/cache/cacheIO.dart:40)
#3      new Cache (package:farmr_client/cache/cacheIO.dart:34)
#4      Blockchain.init (package:farmr_client/blockchain.dart:237)
#5      main (file:///home/runner/work/farmr/farmr/farmr.dart:180)
<asynchronous suspension>
```

**Comment by OutsmartinTech** [comment]
Duplicate of [https://github.com/gilnobrega/farmr/issues/198](https://github.com/gilnobrega/farmr/issues/198)

**Comment by maxcom99** [comment]
Same issue. going to 1.8.3 worked ... nearly a month without a resolution...
