### ISSUE TITLE
SystemD Support

### ISSUE THREAD

**Issue by pcfreak30** [joaquimguimaraes/farmr#34]
For deb/rpm systemd support would be nice.

Here is a starting point:

```
[Unit]
Description=Chia Farmr Monitor
After=network.target
StartLimitIntervalSec=0
[Service]
User=root
Type=simple
Restart=always
RestartSec=1
ExecStart=/usr/bin/farmr
[Install]
WantedBy=multi-user.target
```

**Comment by joaquimguimaraes** [comment]
Hey, this has been in the repo for some days now, and it's included as a user service in the .deb, .rpm packages in v1.4.1
I will be writing documentation on how to enable it.
```systemctl --user enable farmr```
https://github.com/joaquimguimaraes/farmr/blob/main/.github/workflows/farmr.service

**Comment by Feromrk** [comment]
I just installed v1.6.1 on my rpi4 with `sudo apt install ./farmr-ubuntu-aarch64.deb` and could enable it with `systemctl --user enable farmr`. Don't forget to start it aswell with `systemctl --user start farmr`.

**Comment by Knight1** [comment]
Big Problem is that the farmr service does not wait for the harvester to start and just crashes. 

```
● farmr.service - farmr
     Loaded: loaded (/etc/xdg/systemd/user/farmr.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2021-10-31 00:16:30 UTC; 3h 4min ago
    Process: 1810 ExecStart=/usr/bin/farmr headless (code=exited, status=255/EXCEPTION)
   Main PID: 1810 (code=exited, status=255/EXCEPTION)

Oct 31 00:16:19 chia-farmer systemd[1803]: Started farmr.
Oct 31 00:16:19 chia-farmer farmr[1810]: Unable to detect running chia farming/harvesting service.
Oct 31 00:16:29 chia-farmer farmr[1810]: Unhandled exception:
Oct 31 00:16:29 chia-farmer farmr[1810]: Exception: Unable to detect running chia farming/harvesting service.
Oct 31 00:16:29 chia-farmer farmr[1810]: #0      Blockchain.initializePorts (package:farmr_client/blockchain.dart:211)
Oct 31 00:16:29 chia-farmer farmr[1810]: <asynchronous suspension>
Oct 31 00:16:29 chia-farmer farmr[1810]: #1      main (file:///home/runner/work/farmr/farmr/farmr.dart:167)
Oct 31 00:16:29 chia-farmer farmr[1810]: <asynchronous suspension>
Oct 31 00:16:30 chia-farmer systemd[1803]: farmr.service: Main process exited, code=exited, status=255/EXCEPTION
Oct 31 00:16:30 chia-farmer systemd[1803]: farmr.service: Failed with result 'exit-code'.
```

**Comment by joaquimguimaraes** [comment]
Yup I gotta fix that, it didnt happen before
thanks for reporting it!
